# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='海报名字')),
                ('icon', models.CharField(max_length=255, verbose_name='海报封面')),
                ('is_used', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '海报',
            },
        ),
    ]
